### PR TITLE
Add BooruDownloader

### PR DESCRIPTION
**Pull request by fgRuslan**
^_^

### CODE REVIEW

**Comment by soruly** [comment]
When making changes to the list, please read and follow the guideline: https://github.com/soruly/awesome-acg/blob/master/CONTRIBUTING.md

**Comment by fgRuslan** [comment]
I think I fixed it

**Comment by soruly** [comment]
You should add to the list in alphabetical order, not the end of list

**Comment by fgRuslan** [comment]
I'm very sorry :( Is it okay now?

**Pull request merged**
