### PR TITLE
Added Anime X Ninja to Web category

### PR DESCRIPTION
**Pull request by shadow-prince**
Added [AnimeXNinja]( https://github.com/routayush1/animexninja) - Anime Streaming Web App built with NextJS hosted [here](https://animex.ninja/)

### CODE REVIEW

**Comment by soruly** [comment]
Where does the video stream comes from?

**Comment by shadow-prince** [comment]
From [this](https://github.com/routayush1/animexninja-api) api. Which scrapes links from GOGOANIME

**Comment by soruly** [comment]
It seems that's not a legal anime broadcast provider. I see multiple DMCA claims agains gogoanime.

**Comment by shadow-prince** [comment]
Yeah! I'm closing this PR 

> It seems that's not a legal anime broadcast provider. I see multiple DMCA claims agains gogoanime.

**Pull request closed without merging**
