### PR TITLE
Add tags table

### PR DESCRIPTION
**Pull request by zcyzcy88**

### CODE REVIEW

**Comment by kingdido999** [comment]
You need to [sync](https://help.github.com/articles/syncing-a-fork/) your fork before making the PR.

**Comment by zcyzcy88** [comment]
OK.

**Comment by soruly** [comment]
The link seems to be broken. I can't download those tags tables.
If you have those files, would you convert them to csv and create a gist for that?

**Comment by zcyzcy88** [comment]
2017-05-08 04_09_07-gelbooru danbooru sankakucomplex konachan imouto tag _gelbooru _

Mirror:
https://drive.google.com/file/d/0BzmRCFGF56afaEhyczREZ1ByVHc/view?usp=sharing

tip:
If `啊哦，你所访问的页面不存在了。`, do refresh.
If you is not login, do login.
百度云 are seen to have some anti-search-crawler behavior.

**Comment by soruly** [comment]
I think it's better to create a new git repo on GitHub keeping a list of these tags tables.
After that, we can add that repo into this list.

**Comment by zcyzcy88** [comment]
https://github.com/zcyzcy88/TagsTable
It's taken me some time for converting file type.

**Comment by soruly** [comment]
Did you just opened that xls file with Microsoft Excel and saved as HTML page?
That's not a developer-friendly data format.
Try to covert to some standard formats like XML or CSV or JSON , which is easier for programs to read.

**Comment by zcyzcy88** [comment]
Done.

In Firefox, `Ctrl` + drag on `<table>` can select by cell, can copy as plain text with TAB splitted.

Remember:
This is just a guide for using image board, not text corpus.

**Comment by soruly** [comment]
Looks good to me now. Thanks ;)

**Pull request merged**
