### PR TITLE
Add moelib

### PR DESCRIPTION
**Pull request by hexenq**
An alternative solution for #13 . Both appearance and main contents are multi-language supported.

### CODE REVIEW

**Comment by soruly** [comment]
Wow this is great :D
Did you plan to let users to update stuff on moelib? or it will sync with awesome-acg list?

**Comment by hexenq** [comment]
Hello, soruly. It would be great if people can help update stuff on moelib :D  Currently, this website is hosted on Github Pages and the data is wrapped in a json file which can be updated via forks. I had the thought of sync before and it's a pending feature. Some advice? Thanks.

**Comment by kingdido999** [comment]
@hexenq Nice work! I can think of a few ways to automate the syncing process:

1. Download or use GitHub API to access awesome-acg content and convert markdown to proper JSON format, then update moelib with the new json file. It could still involve some manual work.
2. Expose awesome-acg content as API to moelib. This will fully automate the process but it requires extra work on awesome-acg side to sync data between README.md and API service.

**Comment by hexenq** [comment]
@kingdido999 Thank you for your advice. The first one sounds good. One question left is that, currently multi-language data (like description of project in en/jp/zh) is in data json file of moelib . It could involve extra manual work like what you said. Maybe we could use formatted markdown comments in awesome-acg readme.md to describe multi-language information of projects so that the conversion from markdown to json can be done totally automatically with full content?

**Pull request merged**
